function createfigure_rho_loglog(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 26-Jun-2016 13:57:06

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'YMinorTick','on',...
    'YScale','log',...
    'XMinorTick','on',...
    'XTickLabel',{'0.01','0.02','','','0.05','','','','','0.1','0.15'},...
    'XScale','log',...
    'XTick',[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.15],...
    'FontSize',18);
    %'Position',[0.130844594594595 0.129529833856155 0.775 0.795470166143845]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.01 0.15]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create loglog
loglog(X1,Y1,'DisplayName','VFMW (\alpha=0.5)','MarkerSize',10,'Marker','v',...
    'LineWidth',3,...
    'Color',[0 0 1]);

% Create xlabel
xlabel({'\epsilon'});

% Create ylabel
ylabel('Total Average Delay');

% Create legend
legend(axes1,'show');

