function createfigure_sp(X1, Y1, Y2, Y3)
%CREATEFIGURE1(X1, Y1, Y2, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 28-Mar-2016 15:24:38

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1,'LineWidth',2,'FontSize',14);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'DisplayName','C1','LineWidth',2,...
    'Color',[0 0 1]);

% Create xlabel
xlabel({'Time'});

% Create ylabel
ylabel({'Queue Length'});

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.795522186153839 0.86583924466132 0.101298700447207 0.0484633558114931]);

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1,'LineWidth',2,'FontSize',14);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'on');

% Create plot
plot(X1,Y2,'Parent',subplot2,'DisplayName','C2','LineWidth',2,...
    'Color',[1 0 0]);

% Create xlabel
xlabel({'Time'});

% Create ylabel
ylabel({'Queue Length'});

% Create legend
legend2 = legend(subplot2,'show');
set(legend2,...
    'Position',[0.795331101193802 0.566193854590398 0.101298700447206 0.0484633558114933]);

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1,'LineWidth',2,'FontSize',14);
box(subplot3,'on');
grid(subplot3,'on');
hold(subplot3,'on');

% Create plot
plot(X1,Y3,'Parent',subplot3,'DisplayName','C3','LineWidth',2,...
    'Color',[0 1 0]);

% Create xlabel
xlabel({'Time'});

% Create ylabel
ylabel({'Queue Length'});

% Create legend
legend3 = legend(subplot3,'show');
set(legend3,...
    'Position',[0.796071766778218 0.264775414874086 0.101298700447206 0.0484633558114934]);

