function createfigure_power(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 25-Jun-2016 14:43:16

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'FontSize',18);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','VFMW','MarkerSize',10,'Marker','v','LineWidth',3,...
    'Color',[0 0 1]);

% Create xlabel
xlabel({'\alpha value'});

% Create ylabel
ylabel({'Total Average Delay'});

% Create legend
legend(axes1,'show');

