function createfigure_iso(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 14-Dec-2015 22:04:19

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',6,'FontWeight','bold',...
    'FontSize',28);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Case 1','MarkerSize',15,'Marker','diamond',...
    'LineWidth',8,...
    'Color',[1 0 0]);

% Create xlabel
xlabel({'\alpha'},'FontSize',30.8);

% Create ylabel
ylabel({'% Time in Switchover'},'FontSize',30.8);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.67536736616241 0.243304845495441 0.192575402229402 0.0826210804304845]);

