function createfigure_subplot2(X1, YMatrix1, YMatrix2)
%CREATEFIGURE1(X1, YMATRIX1, YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 28-Mar-2016 22:12:56

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'FontSize',14,...
    'Position',[0.131298701298701 0.609775823142456 0.775 0.315224176857544]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','C1','MarkerSize',10,'Color',[0 0 1]);
set(plot1(2),'DisplayName','C2','Color',[1 0 0]);

% Create xlabel
xlabel({'Time'},'FontSize',15.4);

% Create ylabel
ylabel({'Queue Length'},'FontSize',15.4);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.768831168831169 0.852245874326653 0.103030305209192 0.0886524799444992]);

% Create axes
axes2 = axes('Parent',figure1,'LineWidth',2,'FontSize',14,...
    'Position',[0.131298701298701 0.13593861384013 0.775 0.315224176857544]);
box(axes2,'on');
grid(axes2,'on');
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes2,'LineWidth',2);
set(plot2(1),'DisplayName','C2','Color',[1 0 0]);
set(plot2(2),'DisplayName','C3','Color',[0 1 0]);

% Create xlabel
xlabel({'Time'},'FontSize',15.4);

% Create ylabel
ylabel({'Queue Length'},'FontSize',15.4);

% Create legend
legend2 = legend(axes2,'show');
set(legend2,...
    'Position',[0.773593092237417 0.361111119987367 0.101298700447206 0.0886524799444996]);

