function createfigure_rho(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 26-Jun-2016 13:56:51

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'FontSize',18);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','VFMW (\alpha=0.5)','MarkerSize',10,'Marker','s',...
    'LineWidth',3,...
    'Color',[0 0 1]);

% Create xlabel
xlabel({'System Load'});

% Create ylabel
ylabel({'Total Average Delay'});

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.175297624342853 0.810317462304283 0.333928564456957 0.0793650773782578]);

