function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 05-Jan-2017 14:10:50

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'MarkerSize',8,'Marker','s','LineWidth',2.5,...
    'LineStyle','-',...
    'Color',[1 0 1]);

% Create xlabel
xlabel({'Time (s)'});

% Create ylabel
ylabel({'Total Number of Vehicles'});

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',18,'LineWidth',2.5);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.174404764884993 0.815873017859839 0.173214282734053 0.0761904742036545]);

